name: Publishing

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: "yarn"
      - run: yarn
      - run: yarn run build
      - name: Release
        if: github.ref_name == 'main'
        run: npm publish --access public
        working-directory: ./dist/libs/ngx-mapbox-gl
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Next
        if: github.ref_name == 'develop'
        run: npm publish --access public --tag next
        working-directory: ./dist/libs/ngx-mapbox-gl
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
